- name: Instalar apache2 en Debian-Ubuntu
  apt: name=apache2 state=latest
- name: Iniciar y habilitar el servicio Debian-Ubuntu
  service: name=apache2 state=started enabled=true
- name: Copiar fichero de configuracion
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify: restart_httpd