- name: Instalar apache2 en Debian-Ubuntu
  apt: name=apache2 state=latest
  when: ansible_distribution == "Debian" o ansible_distribution == "Ubuntu"
- name: Iniciar y habilitar el servicio Debian-Ubuntu
  service: name=apache2 state=started enabled=true
  when: ansible_distribution == "Debian" o ansible_distribution == "Ubuntu"

- name: Instalar httpd en CentOS
  yum: name=http state=latest
  when: ansible_distribution == "CentOS"
- name: Iniciar y habilitar el servicio CentOS
  service: name=httpd state=started enabled=true
  when: ansible_distribution == "CentOS"


- name: Copiar fichero de configuracion
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify: restart_httpd

- name: Copiar index.html
  template: src=index.html.j2 dest=/var/www/html/index.html

